/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntonaranja;

import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import java.util.Set;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
import utils.ComboItem;
import utils.Message;
import utils.Static;
import utils.TextPrinter;
import utils.Utilities;
import utils.auth;
import utils.httpCall;

/**
 *
 * @author rlobo
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    CambioContraseña ventanaPass;  
    Border border = LineBorder.createGrayLineBorder();
    Recargas recargas;
    ventaPines pines;
    cierreCaja caja;
    ServiciosPublicos servP;   
    exportaVentas exportar;
    int[] files;
    ventanaReporte reporte;
    static int counter = 0;
    static JSONObject json = new JSONObject();
    static ArrayList<ComboItem> elements = new ArrayList<>();
    public home() {
        initComponents();
        llenaTabla();
        Static stat=new Static();
        if(!Static.getPass())menuPedir.setText("Pedir Contraseña: NO");
        else menuPedir.setText("Pedir Contraseña: SI");        
        ImageIcon img = new ImageIcon(getClass().getResource("/puntonaranja/resurces/naranja.png"));
        setIconImage(img.getImage());
        files=new int[10];
        ventanaPass= new CambioContraseña(false);
        recargas=new Recargas();
        pines= new ventaPines();
        servP=new ServiciosPublicos();
        caja=new cierreCaja();
        exportar=new exportaVentas();
        reporte=new ventanaReporte();
        loadNews();
        if(ConfirmaRecarga.consultaSaldo()==null){
            this.setVisible(false);
            new Login().setVisible(true);
        }
         if(Float.parseFloat(Static.getSaldo())>=0) txtSaldo.setText(Static.getSaldo());
         else{ 
             txtSaldo.setText("0.0");             
            JOptionPane.showMessageDialog(null,ConfirmaRecarga.consultaSaldo()+", no se pudo actualizar el saldo", "Error!", JOptionPane.ERROR_MESSAGE);
         }

        keyListeners();
        //keysAdded
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecargas = new javax.swing.JButton();
        btnPines = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnCaja = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaNoti = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblKolbi = new javax.swing.JLabel();
        lblAya = new javax.swing.JLabel();
        lblICE = new javax.swing.JLabel();
        lblESPH = new javax.swing.JLabel();
        lblCNFL = new javax.swing.JLabel();
        lblICETel = new javax.swing.JLabel();
        lblESPHAgua = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBitacora = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        lblNaranja = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuPedir = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        btnRecargas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRecargas.setText("Recargas");
        btnRecargas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecargasMouseClicked(evt);
            }
        });
        btnRecargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargasActionPerformed(evt);
            }
        });

        btnPines.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPines.setText("Venta de Pines");
        btnPines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPinesMouseClicked(evt);
            }
        });
        btnPines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinesActionPerformed(evt);
            }
        });

        btnServicios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnServicios.setText("Servicios Públicos");
        btnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServiciosMouseClicked(evt);
            }
        });

        btnCaja.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCaja.setText("Cierre de caja");
        btnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCajaMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Últimas Noticias");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        label1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        label1.setText("Titulo");

        areaNoti.setEditable(false);
        areaNoti.setColumns(20);
        areaNoti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        areaNoti.setLineWrap(true);
        areaNoti.setRows(5);
        jScrollPane2.setViewportView(areaNoti);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblKolbi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKolbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/kolbi.jpg"))); // NOI18N
        lblKolbi.setText("jLabel2");
        lblKolbi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblKolbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKolbiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKolbiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKolbiMouseExited(evt);
            }
        });

        lblAya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/AYA.jpg"))); // NOI18N
        lblAya.setText("jLabel2");
        lblAya.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAyaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAyaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAyaMouseExited(evt);
            }
        });

        lblICE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/ICE.jpg"))); // NOI18N
        lblICE.setText("jLabel2");
        lblICE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblICE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblICEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblICEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblICEMouseExited(evt);
            }
        });

        lblESPH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/ESPH.jpg"))); // NOI18N
        lblESPH.setText("jLabel2");
        lblESPH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblESPH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblESPHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblESPHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblESPHMouseExited(evt);
            }
        });

        lblCNFL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/CNFL.jpg"))); // NOI18N
        lblCNFL.setText("jLabel2");
        lblCNFL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCNFL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCNFLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCNFLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCNFLMouseExited(evt);
            }
        });

        lblICETel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/ICETel.jpg"))); // NOI18N
        lblICETel.setText("jLabel2");
        lblICETel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblICETel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblICETelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblICETelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblICETelMouseExited(evt);
            }
        });

        lblESPHAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/ESPHAgua.jpg"))); // NOI18N
        lblESPHAgua.setText("jLabel2");
        lblESPHAgua.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblESPHAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblESPHAguaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblESPHAguaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblESPHAguaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKolbi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(lblICE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblICETel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblESPHAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCNFL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblESPH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKolbi)
                    .addComponent(lblICE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblICETel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNFL)
                    .addComponent(lblESPH)
                    .addComponent(lblESPHAgua))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Servicios comunes", jPanel2);

        tblBitacora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblBitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Hora", "Tipo", "Identificador/Num", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBitacora);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Refrescar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Imprimir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Bitacora", jPanel3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Saldo:");

        txtSaldo.setEditable(false);
        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSaldo.setText("0");

        lblNaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/puntonaranja/resurces/puntos naranja.png"))); // NOI18N
        lblNaranja.setText("jLabel2");
        lblNaranja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNaranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNaranjaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNaranjaMouseExited(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu2.setText("Opciones");

        jMenu6.setText("Consulta Saldo");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu6);

        jMenu1.setText("Exportar Ventas");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu1);

        jMenu5.setText("Seleccionar Impresora");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu5);

        menuPedir.setText("Pedir Contraseña: Si");
        menuPedir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPedirMouseClicked(evt);
            }
        });
        jMenu2.add(menuPedir);

        jMenu3.setText("Cambiar Usuario y Terminal");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu3);

        jMenu4.setText("Cerrar Sesión");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRecargas, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(btnServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPines, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(btnCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jTabbedPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPines, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecargas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Información");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void keyListeners(){
        btnCaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent e) {
               if(e.getKeyCode() == KeyEvent.VK_ENTER){ 
                   btnCajaMouseClicked(null);
                }             
            }
         });
        btnCerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent e) {
               if(e.getKeyCode() == KeyEvent.VK_ENTER){ 
                   btnCerrarMouseClicked(null);
                }             
            }
         });
        btnPines.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent e) {
               if(e.getKeyCode() == KeyEvent.VK_ENTER){ 
                   btnPinesMouseClicked(null);
                }             
            }
         });
        btnRecargas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent e) {
               if(e.getKeyCode() == KeyEvent.VK_ENTER){ 
                   btnRecargasMouseClicked(null);
                }             
            }
         });
        btnServicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent e) {
               if(e.getKeyCode() == KeyEvent.VK_ENTER){ 
                   btnServiciosMouseClicked(null);
                }             
            }
         });
    }
    private void llenaTabla(){
        //DefaultTableModel model = new DefaultTableModel();
        //tblBitacora = new JTable(model);
        DefaultTableModel model = (DefaultTableModel) tblBitacora.getModel();
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i=0; i < rowCount; i++) {
            model.removeRow(0);
        }
        files=new int[10];
        String[] bitacora=new auth().bitacora();
        int cuantos=0;
        for(int i=bitacora.length-3;i>=0;i--){
            String[] datos=new auth().returnRow(bitacora[i]).split("&-&");
            if(datos[3].equals("Recargas")&&model.getRowCount()<10){
                model.addRow(new Object[]{datos[1], datos[2], datos[5],datos[4],datos[6]});
                files[cuantos]=i;
                cuantos++;
            }
        }
        //model.addRow(new Object[]{"30/01/2015", "10:30:20", "Kolbi","87878787","1000"});
    }
    
    private void btnPinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPinesActionPerformed

    private void btnRecargasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecargasMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Going out");
        
        recargas.cambioOperadora("",lblKolbi.getIcon());
        recargas.setVisible(true);
    }//GEN-LAST:event_btnRecargasMouseClicked

    private void btnRecargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargasActionPerformed
/**/
    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        closeAll();
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void lblKolbiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKolbiMouseEntered
        // TODO add your handling code here:
        lblKolbi.setBorder(border);        
    }//GEN-LAST:event_lblKolbiMouseEntered

    private void lblKolbiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKolbiMouseExited
        // TODO add your handling code here:        
        lblKolbi.setBorder(null);        
    }//GEN-LAST:event_lblKolbiMouseExited

    private void lblICEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblICEMouseEntered
        // TODO add your handling code here:
        lblICE.setBorder(border);      
                
    }//GEN-LAST:event_lblICEMouseEntered

    private void lblICEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblICEMouseExited
        // TODO add your handling code here:
        lblICE.setBorder(null);      
    }//GEN-LAST:event_lblICEMouseExited

    private void lblAyaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyaMouseEntered
        // TODO add your handling code here:
        lblAya.setBorder(border);      
    }//GEN-LAST:event_lblAyaMouseEntered

    private void lblAyaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyaMouseExited
        // TODO add your handling code here:
        lblAya.setBorder(null);      
    }//GEN-LAST:event_lblAyaMouseExited

    private void lblESPHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblESPHMouseEntered
        // TODO add your handling code here:
        lblESPH.setBorder(border);      
    }//GEN-LAST:event_lblESPHMouseEntered

    private void lblESPHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblESPHMouseExited
        // TODO add your handling code here:
        lblESPH.setBorder(null);      
    }//GEN-LAST:event_lblESPHMouseExited

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
                TextPrinter print =new TextPrinter();
        try {
            print.setPrinter();
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
                        
    }//GEN-LAST:event_jMenu5MouseClicked

    private void lblICEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblICEMouseClicked
        // TODO add your handling code here:
        servP.cambioOperadora("ICE - Cobro de servicios de electricidad");
        servP.setVisible(true);
                
    }//GEN-LAST:event_lblICEMouseClicked

    private void lblKolbiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKolbiMouseClicked
        // TODO add your handling code here:
        recargas.cambioOperadora("Recarga Kolbi",lblKolbi.getIcon());
        recargas.setVisible(true);
    }//GEN-LAST:event_lblKolbiMouseClicked

    private void btnPinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPinesMouseClicked
        // TODO add your handling code here:
        pines.setVisible(true);
    }//GEN-LAST:event_btnPinesMouseClicked

    private void btnServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseClicked
        // TODO add your handling code here:
        servP.cambioOperadora("");
        servP.setVisible(true);
    }//GEN-LAST:event_btnServiciosMouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        try {
            // TODO add your handling code here:
            if(Float.parseFloat(ConfirmaRecarga.consultaSaldo())>=0){
                
                JOptionPane.showMessageDialog(null, "El saldo actual es: "+Static.getSaldo()+" Colones");
                
            }else JOptionPane.showMessageDialog(null, Static.getSaldo());
        } catch (Exception ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu6MouseClicked

    private void lblNaranjaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNaranjaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNaranjaMouseEntered

    private void lblNaranjaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNaranjaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNaranjaMouseExited

    private void lblCNFLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCNFLMouseEntered
        // TODO add your handling code here:
        lblCNFL.setBorder(border);      
    }//GEN-LAST:event_lblCNFLMouseEntered

    private void lblCNFLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCNFLMouseExited
        // TODO add your handling code here:
        lblCNFL.setBorder(null);      
    }//GEN-LAST:event_lblCNFLMouseExited

    private void lblICETelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblICETelMouseClicked
        // TODO add your handling code here:
        servP.cambioOperadora("ICE - Cobro de servicios telefónicos");
        servP.setVisible(true);
    }//GEN-LAST:event_lblICETelMouseClicked

    private void lblICETelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblICETelMouseEntered
        // TODO add your handling code here:
        lblICETel.setBorder(border);     
    }//GEN-LAST:event_lblICETelMouseEntered

    private void lblICETelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblICETelMouseExited
        // TODO add your handling code here:
        lblICETel.setBorder(null);     
    }//GEN-LAST:event_lblICETelMouseExited

    private void lblESPHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblESPHMouseClicked
        // TODO add your handling code here:
        servP.cambioOperadora("ESPH - Electricidad");
        servP.setVisible(true);
    }//GEN-LAST:event_lblESPHMouseClicked

    private void lblAyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyaMouseClicked
        // TODO add your handling code here:
        servP.cambioOperadora("AyA - Cobro de servicios de agua");
        servP.setVisible(true);
    }//GEN-LAST:event_lblAyaMouseClicked

    private void lblCNFLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCNFLMouseClicked
        // TODO add your handling code here:
        servP.cambioOperadora("CNFL - Cobro de servicios de electricidad");
        servP.setVisible(true);
    }//GEN-LAST:event_lblCNFLMouseClicked

    private void lblESPHAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblESPHAguaMouseClicked
        // TODO add your handling code here:
        servP.cambioOperadora("ESPH - Agua");
        servP.setVisible(true);
    }//GEN-LAST:event_lblESPHAguaMouseClicked

    private void lblESPHAguaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblESPHAguaMouseEntered
        // TODO add your handling code here:
        lblESPHAgua.setBorder(border);      
    }//GEN-LAST:event_lblESPHAguaMouseEntered

    private void lblESPHAguaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblESPHAguaMouseExited
        // TODO add your handling code here:
        lblESPHAgua.setBorder(null);      
    }//GEN-LAST:event_lblESPHAguaMouseExited

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        llenaTabla();
        JOptionPane.showMessageDialog(null,"Bitácora actualizada", "Éxito!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        llenaTabla();
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if(tblBitacora.getSelectedRow()>=0){
            reporte.printSelected(files[tblBitacora.getSelectedRow()]);
            reporte.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Haga click en la transacción que desea imprimir", "Atención!", JOptionPane.WARNING_MESSAGE );
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void btnCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseClicked
        // TODO add your handling code here:
        caja.calculaCierre();
        caja.setSaldo();
        caja.setVisible(true);
    }//GEN-LAST:event_btnCajaMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        exportar.llenaTabla();
        exportar.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void menuPedirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPedirMouseClicked
        // TODO add your handling code here:
        int dialogResult=0;
        if(Static.getPass()){
            dialogResult = JOptionPane.showConfirmDialog (null, "¿Le gustaria deshabilitar la contraseña al hacer ventas?","Atención",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                String name="";
                Boolean pass=false;
               
                    while(!pass){
                        //if(!pass)JOptionPane.showMessageDialog(null,"Contraseña incorrecta", "Error", JOptionPane.WARNING_MESSAGE );
                        //name = JOptionPane.showInputDialog(null, "Digite la contraseña para realizar la venta");
                        JPanel panel = new JPanel();
                        JLabel label = new JLabel("Digite la contraseña:");
                        JPasswordField psw = new JPasswordField(10);
                        panel.add(label);
                        panel.add(psw);
                        String[] options = new String[]{"Aceptar", "Cancelar"};
                        int option = JOptionPane.showOptionDialog(null, panel, "Digite la contraseña",
                        JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                        null, options, options[1]);
                        if(option == 0) // pressing OK button
                        {
                            char[] password = psw.getPassword();
                            name=new String(password);
                        }else{
                            pass=true;
                        }
                        if(name.equals(Static.getPassword()))pass=true;
                    }   
                    this.setVisible(true);
                
                if(pass && name.equals(Static.getPassword())){
                    Static.setPass(false);
                    menuPedir.setText("Pedir Contraseña: NO");                
                    try {
                        new auth().escribeFichero("false","Sesion/archivoPidePassword.txt");
                    } catch (IOException ex) {
                        Logger.getLogger(auth.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(null,"Contraseña deshabilitada", "Gracias", JOptionPane.WARNING_MESSAGE );
                                    
                }
            }
        }
        else{
            dialogResult = JOptionPane.showConfirmDialog (null, "¿Le gustaria habilitar la contraseña al hacer ventas?","Atención",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                Static.setPass(true);
                menuPedir.setText("Pedir Contraseña: SI");
                
                try {
                    new auth().escribeFichero("true","Sesion/archivoPidePassword.txt");
                } catch (IOException ex) {
                    Logger.getLogger(auth.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null,"Contraseña habilitada", "Gracias", JOptionPane.WARNING_MESSAGE );
                    
            }
            
        }
        
    }//GEN-LAST:event_menuPedirMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        txtSaldo.setText(Static.getSaldo());
    }//GEN-LAST:event_formMouseMoved

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        int dialogResult=0;
        dialogResult = JOptionPane.showConfirmDialog (null, "El terminal y usuario solo se deben cambiar bajo ordenes del proveedor ¿Desea continuar?","Atención",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            String name="";
                Boolean pass=false;
            while(!pass){
                        //if(!pass)JOptionPane.showMessageDialog(null,"Contraseña incorrecta", "Error", JOptionPane.WARNING_MESSAGE );
                        //name = JOptionPane.showInputDialog(null, "Digite la contraseña para realizar la venta");
                        JPanel panel = new JPanel();
                        JLabel label = new JLabel("Digite la contraseña:");
                        JPasswordField psw = new JPasswordField(10);
                        panel.add(label);
                        panel.add(psw);
                        String[] options = new String[]{"Aceptar", "Cancelar"};
                        int option = JOptionPane.showOptionDialog(null, panel, "Digite la contraseña",
                        JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                        null, options, options[1]);
                        if(option == 0) // pressing OK button
                        {
                            char[] password = psw.getPassword();
                            name=new String(password);
                        }else{
                            pass=true;
                        }
                        if(name.equals(Static.getPassword()))pass=true;
                    }  
            if(pass && name.equals(Static.getPassword())){
            closeAll();
            dispose();
            ventanaPass.setVisible(true);
            }
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaNoti;
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnPines;
    private javax.swing.JButton btnRecargas;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lblAya;
    private javax.swing.JLabel lblCNFL;
    private javax.swing.JLabel lblESPH;
    private javax.swing.JLabel lblESPHAgua;
    private javax.swing.JLabel lblICE;
    private javax.swing.JLabel lblICETel;
    private javax.swing.JLabel lblKolbi;
    private javax.swing.JLabel lblNaranja;
    private javax.swing.JMenu menuPedir;
    private javax.swing.JTable tblBitacora;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables

    private void loadNews() {
        try {
            httpCall hc = new httpCall();
            json = hc.call("noticias");
           /* json =new JSONObject("{\n" +
"    \"Noticia 1\": \"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non mi rutrum, gravida erat ac, accumsan eros. Cras vehicula erat ac orci mattis cursus non nec felis. Donec at risus quam. Sed vel ultrices leo. Aenean urna turpis, volutpat in aliquam eu, egestas at eros. Proin dictum ultrices lacus, consectetur iaculis ligula suscipit ac. Vivamus tempus semper arcu, nec lacinia metus gravida id. Curabitur lobortis nunc at maximus pellentesque. Nullam nec sollicitudin massa. Nulla metus quam, vestibulum eu sollicitudin a, cursus at eros. Cras hendrerit sapien vitae est elementum, a pulvinar felis sagittis.\",\n" +
"    \"Noticia 2\": \"Vestibulum elementum leo sed justo tristique porta. Quisque eleifend dolor et cursus aliquam. Proin mollis ultrices iaculis. Aenean porttitor auctor risus, sit amet mattis nibh rhoncus in. Morbi in sem tellus. Nullam dignissim faucibus purus a blandit. Sed id suscipit odio. Sed ut leo luctus, viverra odio non, blandit risus.\",\n" +
"    \"Noticia 3\": \"Sed rutrum porta faucibus. Suspendisse interdum facilisis eros ac tincidunt. Integer vulputate in orci a commodo. Pellentesque sed nulla tristique, hendrerit urna sodales, porttitor elit. Sed odio purus, dignissim ac lacus at, sagittis ultricies leo. Maecenas at ante malesuada, efficitur nisi quis, volutpat libero. Praesent ut mattis metus. Aliquam erat volutpat. Pellentesque egestas molestie nisl sit amet auctor. Proin vel porttitor lorem, at cursus metus. Vivamus cursus ullamcorper sem, et lobortis libero.\",\n" +
"}");*/
            Set keys = json.keySet();
            Object[] array = keys.toArray();
            String key = "";
            for(int i=0; i<array.length; i++){
                key = (String) array[i];
                //elements.add((String)json.get(key));
                elements.add(new ComboItem(key, (String) json.get(key)));
            }
            TimerTask timerTask = new TimerTask() {

                @Override
                public void run() {
                    if(counter>=elements.size()){
                        counter = 0;
                    }
                    ComboItem noticia = elements.get(counter);
                    label1.setText(noticia.getValue());
                    areaNoti.setText(noticia.getLabel());
                    counter++;
                }
            };

            Timer timer = new Timer("MyTimer");//create a new Timer

            timer.scheduleAtFixedRate(timerTask, 30, 10000);
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void closeAll() {
        ventanaPass.setVisible(false);
        recargas.setVisible(false);
        pines.setVisible(false);
        servP.setVisible(false);
        caja.setVisible(false);
        exportar.setVisible(false);
    }
}
